### ISSUE TITLE
Add performance/context length graph, AUC

### ISSUE THREAD

**Issue by fynnkroeger** [JoshuaPurtell/LRCBench#1]
I think this eval is really interesting and useful! The metric context at which p = 0.5 is also a good one-number-summary. To add more detail, it would be great to see a graph of the performance (y) depending on the things in context (x). With this you could check if models performance drops in different ways, and see what models are best for short/medium context. Then you could also calculate something like the area under curve (optionally until p = 0.5), which would be another useful one-number-summary.

**Comment by JoshuaPurtell** [comment]
Hey! Let's implement this, because yeah a model with scores 1,1,1....,1,.5 is quite a bit better than 1,.9,.8,....,.5 even if they have the same breaking point.

The logic is straightforward, do you have any suggestions for the best way to visualize this? I think in the terminal I'd use colored bars a la something like tqdm to indicate, but for the GitHub readme I'm not sure what the right form factor is

**Comment by JoshuaPurtell** [comment]
@fynnkroeger Can you look at the scores in the readme and lmk if that's a good format?

**Comment by fynnkroeger** [comment]
I think for text only this is good, but I would also love a (simple) graph that is embedded as a png (that works in github readme i think). Somethink kind of like this:

![plot](https://github.com/user-attachments/assets/daa08f5f-849e-4179-a857-3f13964fecd6)

i think this is faster to understand the results with, and more easily compare more models than with text only. I also think it would not be too crowded as many models fall off quickly.

also, i think it would make sense to add a horizontal line for the stop criteria.

Thanks a lot for responding so quickly!

code (made by chatgpt with demo values)
```
import matplotlib.pyplot as plt

# Data
y_gemini = [10, 10, 10, 7, 8, 8, 3, 8, 4, 4]
y_claude = [10, 10, 10, 10, 10, 10, 9, 4, 1]

# Updated x values
x_values = [1, 2, 5, 10, 20, 30, 50, 75, 100, 150, 200, 300]
x_gemini = x_values[:len(y_gemini)]
x_claude = x_values[:len(y_claude)]

# Plotting with updated x values
plt.figure(figsize=(10, 6))
plt.plot(x_gemini, y_gemini, marker='o', linestyle='-', label='Gemini-1.5-pro')
plt.plot(x_claude, y_claude, marker='o', linestyle='-', label='Claude-3-5-sonnet-20240620')

# Adding labels and title
plt.xlabel('X Values')
plt.ylabel('Values')
plt.title('Line Graph of Gemini-1.5-pro and Claude-3-5-sonnet-20240620 Data with Updated X Values')
plt.legend()
plt.grid(True)

# Show plot
plt.show()
```

**Comment by fynnkroeger** [comment]
Maybe "Best Score" could be renamed to something like "usable context" or "good performance for n examples", otherwise sounds like the best of multiple runs right now. 
best streak could also be renamed, maye something like "perfect score up to", but this is also good as it its.

**Comment by fynnkroeger** [comment]
Another option for how to do it in a table:
![table](https://github.com/user-attachments/assets/f1256b81-9085-4bc7-a830-5a9f79c09959)
from the jamba 1.5 paper https://arxiv.org/abs/2408.12570

**Comment by JoshuaPurtell** [comment]
I really like the idea of showing effective context length. I'm not sure the graphs are super readable, but let's include them!

Going to close this issue, feel free to open a PR with further changes if you'd like but feel like main contains most of the suggestions here as of last PR
